### ISSUE TITLE
echo-message support only shows the first line when sending multiple lines

### ISSUE THREAD

**Issue by Mikaela** [weechat/weechat#1944]
## Bug summary

When I paste and send multiple lines from WeeChat to `echo-message` capable server with `echo-message` enabled, only the first line is displayed to me, while from another client I can see them all.

Sample text:

```
# Display key ascii art on connection. Makes noticing changed keys easier,
# although it's ambiguous and similar pattern may go past unnoticed.
VisualHostKey yes
```

(This is OpenSSH client config)

## Steps to reproduce

1. Add `echo-message` to `irc.server_default.capabilities`
2. Connect to `echo-message` capable server (irc.etro.mikaela.info:6697)
3. Copy-paste multiple lines to WeeChat and choose to send it.

## Current behavior

I only see the first line I send, `2023-W22-1 15:17:03 +0300 <~Mikaela> # Display key ascii art on connection. Makes noticing changed keys easier,`

## Expected behavior

I see all three lines like all the other users in the room.

## Suggested solutions

Display all sent messages once they are echoed by the server?

## Additional information

- `/v -o` is unaffected for some reason.

---

- WeeChat version: WeeChat 4.0.0-dev (git: v3.8-492-g193d29028) [compiled on May 28 2023 23:06:25]
- OS, distribution and version: Debian GNU/Linux 11 (bullseye)
- Terminal: foot version: 1.14.0 -pgo +ime +graphemes -assertions
- Terminal multiplexer (screen/tmux/…/none): tmux 3.1c

**Comment by flashcode** [comment]
Hi,
I just tested with latest master branch: I pushed some commits after your version, to add the `/action` command, and refactorized a lot the way user messages are displayed.
Maybe there was a bug yesterday, but now I'm not able to reproduce the issue (even on your test server): the subsequent lines are properly displayed, even if they are displayed after some delay (due to anti-flood mechanism).
Could you please test with latest master and confirm if it's OK for you as well?
Thanks.

**Comment by Mikaela** [comment]
I am using the weechat.org repository so I guess this will wait until tomorrow?

**Comment by flashcode** [comment]
Yes, but I forgot to mention I also tested with your exact version (commit 193d29028) and it works as well for me.

By the way you don't need to enable explicitly "echo-message", all supported capabilities are enabled by default.

**Comment by Mikaela** [comment]
I am still reproducing this on 

- WeeChat 4.0.0-dev (git: v3.8-500-gc96cc7a00) [compiled on May 29 2023 23:06:23]
- Upgraded 8 times, first start: Fri Mar 24 10:40:30 2023, last start: Tue May 30 08:13:47 2023

I have disabled flood proection on the server,

```
  irc.server.etro.anti_flood_prio_high           integer  0
  irc.server.etro.anti_flood_prio_low            integer  0
```

I do have some scripts

```
2023-W22-2 08:16:20 +0300 Scripts loaded:
2023-W22-2 08:16:20 +0300    ia   colorize_lines.pl 4.0 (Colorize users' text in chat area with their nick color, including highlights)
2023-W22-2 08:16:20 +0300  * ia   highmon.pl 2.7 (Highlight Monitor)
2023-W22-2 08:16:20 +0300    ia   pushover.pl 2.0 (Send push notifications to your mobile devices using Pushover)
2023-W22-2 08:16:20 +0300    ia   unset_unused.pl 0.5 (unset script option(s) from not installed scripts (YOU ARE USING THIS SCRIPT AT YOUR OWN RISK!))
2023-W22-2 08:16:20 +0300    ia   automode.py 0.1.4 (Script for auto op/voice users when they join.)
2023-W22-2 08:16:20 +0300  * ia   autosort.py 3.9 (Flexible automatic (or manual) buffer sorting based on eval expressions.)
2023-W22-2 08:16:20 +0300    ia   chanop.py 0.3.5 (Helper script for IRC Channel Operators)
2023-W22-2 08:16:20 +0300  * ia   colorize_nicks.py 30 (Use the weechat nick colors in the chat area)
2023-W22-2 08:16:20 +0300  * ia   go.py 2.8 (Quick jump to buffers)
2023-W22-2 08:16:20 +0300    ia   listbuffer.py 0.8.2 (A common buffer for /list output.)
2023-W22-2 08:16:20 +0300    ia   prism.py 0.2.12 (Taste the rainbow.)
2023-W22-2 08:16:20 +0300    ia   weestats.py 0.4 (Useless statistics about your open buffers and windows)
```

and some triggers

```
2023-W22-2 08:16:40 +0300 Triggers enabled
2023-W22-2 08:16:40 +0300 List of triggers:
2023-W22-2 08:16:40 +0300   beep: print =? /1
2023-W22-2 08:16:40 +0300   cmd_pass: modifier(5000|input_text_display;5000|history_add;5000|irc_command_auth) ~1
2023-W22-2 08:16:40 +0300   cmd_pass_register: modifier(5000|input_text_display;5000|history_add;5000|irc_command_auth) ~1
2023-W22-2 08:16:40 +0300   msg_auth: modifier(5000|irc_message_auth) ~1
2023-W22-2 08:16:40 +0300   server_pass: modifier(5000|input_text_display;5000|history_add) ~1
2023-W22-2 08:16:40 +0300   whois_on_query: signal(irc_pv_opened) /1
```

Does anything look like it could be causing this?

**Comment by trygveaa** [comment]
I can't reproduce either. I tried both with and without `draft/multiline`.

@Mikaela: None of those scripts or triggers look relevant to me, but maybe some other options you have changed? Can you reproduce with a new weechat instance (run `weechat -t`)? Also, can you post the output of `/cap` when run on the server you're experiencing the issue with.

**Comment by Mikaela** [comment]
I am unable to reproduce it with `weechat -t`

```
2023-W22-3 12:39:19 +0300 -- irc: client capability, server supports: account-notify account-tag away-notify batch cap-notify chghost draft/account-registration=before-connect draft/channel-rename draft/chathistory draft/event-playback draft/languages=17,en,~bs,~de,~el,~en-AU,~es,~fi,~fr-FR,~it,~nl,~no,~pl,~pt-BR,~ro,~sq-AL,~tr-TR,~zh-CN draft/multiline=max-bytes=4096,max-lines=100 draft/persistence draft/read-marker draft/relaymsg=/ echo-message ergo.chat/nope extended-join extended-monitor invite-notify labeled-response message-tags multi-prefix sasl=PLAIN,EXTERNAL server-time setname sts=duration=2765100,port=6697,preload userhost-in-names znc.in/playback znc.in/self-message
2023-W22-3 12:39:19 +0300 -- irc: client capability, currently enabled: account-notify away-notify batch cap-notify chghost draft/multiline echo-message extended-join invite-notify message-tags multi-prefix sasl server-time setname userhost-in-names znc.in/self-message
```

**Comment by flashcode** [comment]
Hi,
I see you closed the issue, OK for me, but it would be still interesting to understand what in your config/scripts/triggers is causing the issue, there may be a real issue there.
Feel free to comment here if you find anything relevant, thanks!

**Comment by Mikaela** [comment]
I never discovered anything relevant or had energy to figure it out, instead just having this thread as unread in my email and I am only commenting this update for having cleaned up 500 emails today including all those I left unread for ages.
