### ISSUE TITLE
weechat stuck at "downloading list of scripts"

### ISSUE THREAD

**Issue by yoshuawuyts** [weechat/weechat#359]
tried reinstalling (through `brew`), but can't get it to work. Any suggestions on what I might do?

**Comment by flashcode** [comment]
If you have problem with downloading of scripts, you could try `/set script.scripts.url_force_https off`, which is less secured but can help if you have SSL errors when downloading (on some OS).

**Comment by yoshuawuyts** [comment]
That seems to have worked wonders. Was running on `OS X` yosemite; in case you're looking for something in particular, [my dotfiles are here](https://github.com/yoshuawuyts/dotfiles/tree/master/weechat). Thanks!

**Comment by flashcode** [comment]
WeeChat uses inyernally curl to download the file.
So you could try that in your shell:
`curl -O https://weechat.org/files/plugins.xml.gz`

**Comment by yoshuawuyts** [comment]
odd, that works normally. Also haven't setup any dotfiles for curl that might interfere. Hmmm.

**Comment by flashcode** [comment]
I'm closing the issue, since I'm not able to test that on OS X, and can't reproduce the problem on any other OS (Linux, *BSD, GNU/Hurd, Cygwin, ...).

**Comment by yoshuawuyts** [comment]
Confirming that it's solved by doing the steps you mentioned before.

**Comment by nlitsme** [comment]
A reason why scripts do not seem to load on OSX: forgot to pass the `--with-python` option to `brew install weechat`.

**Comment by anticitizen4** [comment]
I had this issue right now. Reinstalling `--with-python` didn't help. Manually downloading `plugins.xml.gz` and putting it in `~/.weechat/script/` worked for me though.

**Comment by flashcode** [comment]
The problem is maybe the check of SSL certificate on weechat.org.
I removed the option because now weechat.org doesn't accept connections without SSL.

So you could check why curl does not find certificates (check option weechat.network.gnutls_ca_file in weechat, and that it points to a valid file).

**Comment by anticitizen4** [comment]
I actually had the same problem with `irssi`. It also wouldn't download scripts. Turns out MacOS stopped supplying some sort of headers for `openssl` since 10.11, which now needed to be manually installed through `cpan`. [This solution](https://github.com/irssi/scripts.irssi.org/issues/226#issuecomment-234646040) helped me fix irssi, but weechat still doesn't work. Maybe another certificate is required.

**Comment by gtramontina** [comment]
Anyone else still experiencing this? I'm running on macOS High Sierra, fresh `weechat` install, and `/script` hangs for me… `curl -O https://weechat.org/files/plugins.xml.gz` works fine.

Tried @anticitizen4's suggestion to no avail…

**Comment by puremourning** [comment]
Yes, I am having the exact same behaviour as @gtramontina on High Sierra, completely new install from homebrew.

**Comment by spadgett** [comment]
I'm seeing this as well. No errors running the curl command. `url_force_https off` also doesn't work for me.

```
/set script.scripts.url_force_https off
Error: option "script.scripts.url_force_https" not found
```

I installed from homebrew

**Comment by spadgett** [comment]
This fixed it for me:

```
brew uninstall weechat
brew install weechat --with-aspell --with-python --with-perl
```

I had previously installed with

```
brew install weechat --with-aspell --with-curl --with-python --with-perl --with-ruby --with-lua --with-guile
```

**Comment by suchkultur** [comment]
Thank you @spadgett, this exact same procedure solved it for me, too (weechat 2.0.1 on macos).

**Comment by neverfox** [comment]
@spadgett Did you have to drop all of them to get it to work? For example, I need lua support. In general, that feels like a workaround not a solution, because it should work with any of the supported features, don't you think?

**Comment by jsatk** [comment]
This no longer appears to work @nicexe . 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/1005550/51571864-50057100-1e58-11e9-9c09-02828897f310.png">

**Comment by jsatk** [comment]
This appears to still be a very real issue. I've been chatting in #weechat on Freenode about it. Please re-open.

**Comment by flashcode** [comment]
@jsatk: if you're using Mac OS and Homebrew, I suggest to report the problem to the Homebrew team then, since the workaround above was supposed to work.
The brew package is not maintained by me, so I can not help with that (and I have absolutely no way to install OS X in a VM to try/help).

**Comment by ericboehs** [comment]
Brewed `curl` is no longer provided as a dependency to the `weechat` formula in Homebrew. It will fall back to the system `curl` and should now work.

`brew uninstall --force weechat; brew install weechat` should get you going.

Thanks to Mike on the Homebrew team for sticking with us and getting it fixed (see https://github.com/Homebrew/homebrew-core/issues/36342 and https://github.com/Homebrew/homebrew-core/pull/36409 for the history on the resolution).

**Comment by flashcode** [comment]
@ericboehs: thanks for your help and the news in this issue, I hope this will help people using Mac OS.

**Comment by jesse-c** [comment]
Confirmed working on macOS 10.14.2 (18C54). Thank you!

**Comment by jsatk** [comment]
Thank you!

**Comment by flashcode** [comment]
Hi,
I added a different way to download scripts using threads, this should fix the issue.
See my comment here: https://github.com/weechat/weechat/issues/1723#issuecomment-1711448127
Please try, your feedback is important.
If the problem is fixed, this is going to be merged.
Thanks!
