### ISSUE TITLE
Channel names encoding

### ISSUE THREAD

**Issue by programadorhedonista** [weechat/weechat#482]
I use an irc network (_chathispano_) that it use iso-8859-15, and the channel names are iso-8859-15 too.
But also, some people use utf-8 for theirs messages.

Configuring the default charset to iso-8859-15 in weechat, 
- With weechat 1.2 I can see all messages (including **utf-8** messages)  and all iso-8859-15 channelnames.
- Now, with weechat from github _(master branch, commit ca6854e207d5ac9ca3f1377a02f25210f2ef4c36)_,  the "iso-8859-15 channel names" are corrupted with "?".

**Comment by Mikaela** [comment]
I think this is duplicate of https://github.com/weechat/weechat/issues/218 or at least related to it or that fix.

**Comment by flashcode** [comment]
Yes it should be fixed by #218, so if possible, please try with latest development version (1.3-rc1), which is stable for daily use.

**Comment by programadorhedonista** [comment]
As I said, *this problem* is with the last dev version.
There is no problem with weechat 1.2 version.
So #218 must be a different problem.

**Comment by flashcode** [comment]
Can you try with a default config, in a new WeeChat session, to be sure it's not an upgrade problem or something like that?
If you are able to reproduce the problem, please tell me the exact steps, this will make things easier for me to fix the problem.
I still think it's related to #218, so maybe that's a regression caused by this fix.

**Comment by programadorhedonista** [comment]
after `$ rm -rf ~/.weechat` the problem persist.

Steps to test:
`server irc.chathispano.com/6667`  and a channel with a ISO encoded character is his name. For example  `#matemáticas`

With the default charset config,
>    decode "iso-8859-1"
>    encode ""

I can't join this channel, so I edit `encode = "iso-8859-1"` (or -15)


Now, 
- with weechat 1.2,  I can send `/MODE #matemáticas` and see the modes,  and I can `/JOIN #matemáticas`.
- with weechat git,  `/MODE #matemáticas` reply _#matemáticas: No such channel_,  and `/JOIN` works but show _#matem?aticas_ in status bar.

.
P.S. console locale **LANG=es_ES.UTF-8**

**Comment by flashcode** [comment]
OK, so I understood your problem. Let me explain what WeeChat did before the fix #218, and the current behavior.

In WeeChat <= 1.2, the whole message was decoded, including the nick, host, channel, target, and the body of messate ifself.
For example:

    :nick!nick@example.com PRIVMSG #matemáticas :this is a test

Here everything was decoded and encoded when receiving/sending to the IRC server.
That was wrong and caused bugs (sometimes channel not found if it's decoded by WeeChat).
Anyway, decoding the whole message was a bug, and for me charset options should apply only on the user message, nothing else (here: `this is a test`).

The current behavior in WeeChat >= 1.3-dev is to decode the user message only.
Since WeeChat is full UTF-8 (everything is stored as UTF-8 internally), this is a problem for channels with ISO chars because there's no conversion any more (from UTF-8 to ISO or reverse).
There's a workaround to join or interact with ISO channels, using /eval command (and .autojoin options in server are auto-evaluated).
That means you can do that:

    /eval /mode #matem${\xe1}ticas
    /eval /join #matem${\xe1}ticas
    /set irc.server.freenode.autojoin "#matem${\xe1}ticas"

I agree this is a bit weird to have to do that, and this lead to some display problem in name after, because the channel name is now stored as-is in WeeChat (in ISO and not as UTF-8, like everything else). That's why you'll see chars `?` in status bar or in channel when the channel name is displayed (and even in input bar when you complete the channel name).
But apart from these small problems, everything should work fine with the channel once joined.

**So what can we do for that?**

*Note: this solution could be developed for the future, not for 1.3, which should be released next days.*

As I said, I think current charset options should apply only to user messages, not channel names. This is because on the same IRC server you can have UTF-8 and ISO channels (it would be really better if people use UTF-8 everywhere, but for now, we must support both...).

So what about adding other charset options that would tell WeeChat to encode one specific channel to ISO (or all channels on a server if you are sure to always use ISO)?
So that internally the channel will be stored as UTF-8 in WeeChat (no more display bug), and WeeChat will have to decode/encode the channel name in all messages (from or to the server).
The channel can then have different encoding from the messages you are sending (this should happen rarely though).

**And what can we do for the version 1.3?**

Since the version 1.3 should be released soon, I see only two options:
1. keep the behavior as-is, with the drawbacks mentioned above: need to use /eval to join ISO channels, and the `?` displayed in names
2. add a temporary option to switch to old behavior, ie decode/encode channel inside messages, according to your existing charset options (waiting for a better solution).

Please give me a fast feedback on that, because the release of 1.3 is still scheduled for Aug 16th
(the date can be shifted if this bug is considered as blocking).

**Comment by programadorhedonista** [comment]
For now I think that option 2 is better. Writing log with � in the file name is ugly :)

**Comment by programadorhedonista** [comment]
Thank you, flashcode. Now I can see the ISO channels correctly :)


( Just a comment.  The option `irc.network.channel_encode = on` *don't work exactily like* it was in WeeChat <= 1.2
This irc network permit to use ISO characters in the host name (a hostname cloak),
and now, with `channel_encode = on`, those characters are shown with `"?"` in JOIN, etc.
A minor problem...)

**Comment by flashcode** [comment]
Yes you're right, with the option enabled, only the channel is decoded (in addition to the user message).
The nick/host are not decoded any more. So I'll update the help on option.
And all these things should be improved in future (for now I don't know exactly how).

**Comment by flashcode** [comment]
I changed the behavior in version 2.7-dev, to fix the issue #832, so now the default is to decode/encode the whole IRC message. See the commit and the release notes for more info: 39b6fb61370de2591146460bd5414955a234801e and https://weechat.org/files/releasenotes/ReleaseNotes-devel.html#v2.7_irc_message_decoding.
